package com.twistlet.hemlock.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HemlockPatient generated by hbm2java
 */
@Entity
@Table(name="hemlock_patient"
)
public class HemlockPatient  implements java.io.Serializable {


     private Integer id;
     private HemlockIdType hemlockIdType;
     private String idNo;
     private Date birthDate;
     private String contactNo;

    public HemlockPatient() {
    }

    public HemlockPatient(HemlockIdType hemlockIdType, String idNo, Date birthDate, String contactNo) {
       this.hemlockIdType = hemlockIdType;
       this.idNo = idNo;
       this.birthDate = birthDate;
       this.contactNo = contactNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_type")
    public HemlockIdType getHemlockIdType() {
        return this.hemlockIdType;
    }
    
    public void setHemlockIdType(HemlockIdType hemlockIdType) {
        this.hemlockIdType = hemlockIdType;
    }

    
    @Column(name="id_no", length=15)
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birth_date", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="contact_no", length=15)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }




}


