package com.twistlet.hemlock.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HemlockRole generated by hbm2java
 */
@Entity
@Table(name="hemlock_role"
)
public class HemlockRole  implements java.io.Serializable {


     private String roleName;
     private String roleDescription;
     private Set<HemlockUserRole> hemlockUserRoles = new HashSet<HemlockUserRole>(0);

    public HemlockRole() {
    }

	
    public HemlockRole(String roleName) {
        this.roleName = roleName;
    }
    public HemlockRole(String roleName, String roleDescription, Set<HemlockUserRole> hemlockUserRoles) {
       this.roleName = roleName;
       this.roleDescription = roleDescription;
       this.hemlockUserRoles = hemlockUserRoles;
    }
   
     @Id 

    
    @Column(name="role_name", unique=true, nullable=false, length=50)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    
    @Column(name="role_description", length=50)
    public String getRoleDescription() {
        return this.roleDescription;
    }
    
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hemlockRole")
    public Set<HemlockUserRole> getHemlockUserRoles() {
        return this.hemlockUserRoles;
    }
    
    public void setHemlockUserRoles(Set<HemlockUserRole> hemlockUserRoles) {
        this.hemlockUserRoles = hemlockUserRoles;
    }




}


