package com.twistlet.hemlock.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HemlockIdType generated by hbm2java
 */
@Entity
@Table(name="hemlock_id_type"
)
public class HemlockIdType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<HemlockPatient> hemlockPatients = new HashSet<HemlockPatient>(0);

    public HemlockIdType() {
    }

    public HemlockIdType(String name, Set<HemlockPatient> hemlockPatients) {
       this.name = name;
       this.hemlockPatients = hemlockPatients;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hemlockIdType")
    public Set<HemlockPatient> getHemlockPatients() {
        return this.hemlockPatients;
    }
    
    public void setHemlockPatients(Set<HemlockPatient> hemlockPatients) {
        this.hemlockPatients = hemlockPatients;
    }




}


